/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    'overview',
    'getting-started',
    {
      label: 'Guides',
      type: 'category',
      link: { type: 'doc', id: 'guides/index' },
      items: [ { type: 'autogenerated', dirName: 'guides',}, ],
    },
    {
      label: 'ngrok Cloud Edge',
      type: 'category',
      link: { type: 'doc', id: 'cloud-edge/index' },
      items: [ { type: 'autogenerated', dirName: 'cloud-edge', }, ],
    },
    {
      label: 'ngrok Secure Tunnels',
      type: 'category',
      link: { type: 'doc', id: 'secure-tunnels/index' },
      items: [ { type: 'autogenerated', dirName: 'secure-tunnels', }, ],
    },
    'platform',
    {
      label: 'Using ngrok with',
      type: 'category',
      link: { type: 'doc', id: 'using-ngrok-with' },
      items: [ { type: 'autogenerated', dirName: 'using-ngrok-with', }, ],
    },
    {
      label: 'Reference',
      type: 'category',
      items: [ 
        {
          type: 'category',
          label: 'ngrok agent',
          link: { type: 'doc', id: 'ngrok-agent/index' },
          items: [ { type: 'autogenerated', dirName: 'ngrok-agent', }, ],
        },
        'reference/api/index-2',
        {
          type: 'doc',
          label: 'Error Codes',
          id: 'reference/errors/index-2'
        },
        'reference/event-sources',
        'reference/event-filtering',
        'http-header-templates',
      ],
    },
    'faq',
  ],

  events: [
    'reference/event-sources',
    'reference/event-filtering',
  ],

  errors: [
    { type: 'autogenerated', dirName: 'reference/errors', }
  ],
};

module.exports = sidebars;
