name: Index Dev
on:
  pull_request: {}
  # TODO: Remove push to master once we have algolia_prod.yml
  push:
    branches:
      - master
jobs:
  index-dev:
    runs-on: ubuntu-latest
    name: test the action
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.DEV_ALGOLIA_APPLICATION_ID }}
          algolia_api_key: ${{ secrets.DEV_ALGOLIA_API_KEY }}
          file: 'algolia_dev.config.json'
