name: Update Algolia Doc Search Index
on:
  push:
    branches:
      - main
jobs:
  index-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.DEV_ALGOLIA_APPLICATION_ID }}
          algolia_api_key: ${{ secrets.DEV_ALGOLIA_API_KEY }}
          file: 'algolia_dev.config.json'
