name: CI Checks

permissions: {}

on: push

jobs:
  ci-checks:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v4
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          cache: 'pnpm'
      - name: 'Create env file'
        run: |
          echo DEPLOY_ENV=dev > .env
      - name: Install Dependencies 📥
        run: pnpm install --frozen-lockfile
