name: CI Checks

permissions: {}

on: push

jobs:
  ci-checks:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          cache: 'pnpm'
      - name: 'Create env file'
        run: |
          echo DEPLOY_ENV=dev > .env
      - name: Install Dependencies 📥
        run: pnpm install --frozen-lockfile
